highlighter: rouge
github: [Repository metadata]

baseurl: "http://www.wesandersoncharacters.com"
livereload: true

collections:
  movie:
    output: true
    output_ext: .html
    permalink: /movie/:path/

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true